repos:
  - repo: local
    hooks:
      - id: check-docs
        name: Check Command Documentation
        description: Ensures that all of the commands in the terminal are included in Hugo.
        language: python
        pass_filenames: false
        args:
          [
            "--ignore-files=settings_controller.py,featflags_controller.py,keys_controller.py,degiro_controller.py,",
            "--ignore-commands=login,alswe,infoswe,goodness,resources,yf,yolo,from,to,featflags,guess,settings,survey,intro"
          ]
        entry: python custom_pre_commit/check_doc.py
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [css, markdown, text, svg]
      - id: trailing-whitespace
        exclude_types: [html, markdown, text]
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        entry: flake8 --ignore=E203,W503 --max-line-length=122 --exclude ./build/pyinstaller/*
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        entry: codespell
        args:
          [
            "--ignore-words-list=commun,ro,zar,vie,hel,zlot,ba,buil,coo,ether,hist,hsi,mape,navagation,operatio,pres,ser,yeld,shold,ist,varian,datas,ake,creat,statics",
            "--quiet-level=2",
            "--skip=./tests,.git,*.css,*.csv,*.html,*.ini,*.ipynb,*.js,*.json,*.lock,*.scss,*.txt,*.yaml,build/pyinstaller/*,./website/config.toml",
          ]
  - repo: local
    hooks:
      -   id: mypy
          name: mypy
          description: ''
          entry: mypy
          language: python
          'types_or': [python, pyi]
          args: ["--ignore-missing-imports", "--scripts-are-modules"]
          require_serial: true
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        name: Strip notebooks output
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint openbb_terminal terminal.py tests -j 4
        language: system
        types: [python]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args:
          ["--baseline", ".secrets.baseline", "--exclude-files", "cassettes/*", "--exclude-files", "website/content/api/*"]
        exclude: package.lock.json
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: local
    hooks:
      - id: reserved_args
        name: Check validity of reserved arguments
        entry: python custom_pre_commit/check_reserved_args.py
        language: system
        types: [python]
