[tool.poetry]
name = "OpenBBTerminal"
version = "1.9.1"
description = "Investment Research for Everyone, Anywhere."
license = "MIT"
authors = ["Didier Rodrigues Lopes"]
packages = [
    { include = "openbb_terminal" },
]
readme = "openbb_terminal/SDK_README.md"
homepage = "https://openbb.co/"
repository = "https://github.com/OpenBB-finance/OpenBBTerminal"
documentation = "https://openbb-finance.github.io/OpenBBTerminal/"

[tool.poetry.scripts]
openbb = 'openbb_terminal.terminal_controller:parse_args_and_run'

[tool.poetry.dependencies]
python = "^3.8,<3.11, !=3.9.7"
scipy = "1.8.1"
iso8601 = "^0.1.14"
FundamentalAnalysis = "^0.2.6"
requests = "^2.25.1"
alpha-vantage = "^2.3.1"
finviz = "^1.3.4"
bs4 = "^0.0.1"
rapidfuzz = "^1.1.1"
yfinance = "0.1.74"
psaw = "^0.0.12"
praw = "^7.1.4"
Quandl = "^3.6.0"
pytrends = "^4.7.3"
matplotlib = "^3.3.3"
plotly = "^5.0.0"
prompt-toolkit = "^3.0.16"
jupyter = "^1.0.0"
jupyterlab = "^3.2.4"
mplfinance = "^0.12.7-alpha.7"
seaborn = "^0.11.0"
fredapi = "^0.4.3"
screeninfo = "^0.6.7"
robin-stocks = "^2.0.3"
pyally = "^1.1.2"
pycoingecko = "^2.2.0"
detecta = "^0.0.5"
tradingview-ta = "^3.2.3"
finvizfinance = "^0.14.0"
statsmodels = "^0.13"
pyportfolioopt = "^1.4.1"
python-coinmarketcap = "^0.2"
oandapyV20 = "^0.6.3"
valinvest = "^0.0.2"
bt = "^0.2.9"
vaderSentiment = "3.3.2"
GitPython = "^3.1.17"
pyEX = "^0.5.0"
sentiment-investor = "^2.0.0"
fred = "^3.1"
financedatabase = "1.0.2"
reportlab = "^3.6.2"
holidays = "^0.14.2"
degiro-connector = "^2.0.3"
python-binance = "^1.0.15"
python-i18n = "^0.3.9"
thepassiveinvestor = "^1.0.10"
pymongo = "^3.11"
pandas-ta = "^0.3.14-beta.0"
pyrsistent = "^0.18.0"
openpyxl = "^3.0.9"
jsonschema = "^3.2.0"
pandas = "^1.5.0"
pandas-market-calendars = "~3.2"
ipympl = "^0.8.2"
voila = "^0.3.0"
rich = "^12.6.0"
investpy = "^1.0.7"
dnspython = "^2.1.0"
python-dotenv = "^0.19.2"
Pygments = "^2.11.2"
ascii-magic = "^1.6"
squarify = "^0.4.3"
finnhub-python = "^2.4.10"
linearmodels = "^4.25"
ipywidgets = "^7.7.0"
Jinja2 = "^3.0.3"
Riskfolio-Lib = "^3.1.1"
ccxt = "^1.91.60"
html5lib = "^1.1"
feedparser = "^6.0.10"
pyinstaller = {version = "^4.10", optional = true}
jupyterlab-code-formatter = {version = "^1.4.10", optional = true}
jupyterlab-lsp = {version = "^3.10.1", optional = true}
jedi-language-server = {version = "^0.35.1", optional = true}
tokenterminal = "^1.0.1"
torch = {version = "1.11.0", optional = true}
streamlit = "^1.12.2"
charset-normalizer = "2.1.1"
watchdog = "^2.1.9"
pythclient = "^0.1.2"
ipyflex = "^0.2.4"
"ruamel.yaml" = "^0.17.21"
setuptools = "^65.4.1"
investiny = "^0.5.0"
numpy = "1.23.4"
papermill = "^2.4.0"
stocksera = "^0.1.21"
ipython = "8.5.0"
protobuf = "3.20.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pylint = "2.15.2"
flake8 = "^3.9.0"
mypy = "^0.930"
mock = "^4.0.3"
codespell = "^2.0.0"
pyupgrade = "^2.11.0"
sphinx = "^4.5.0"
myst-parser = "^0.15.2"
black = {extras = ["jupyter"], version = "^22.1.0"}
bandit = "^1.7.0"
coverage = ">=5.5"
vcrpy = "^4.1.1"
pytest-mock = "^3.6.1"
pytest-recording = "^0.12.0"
types-pytz = "^2021.3.1"
types-requests = "^2.26.0"
types-PyYAML = "^6.0.1"
types-python-dateutil = "^2.8.3"
types-setuptools = "^57.4.7"
pre-commit = "^2.16.0"
pytest-cov = "^3.0.0"
types-six = "^1.16.12"
nbmake = ">0.5.0"

[tool.poetry.extras]
prediction = ["torch"]
jupyterlab = ["jupyterlab-code-formatter", "jupyterlab-lsp", "jedi-language-server"]
installer = ["pyinstaller"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pydocstyle]
convention = "numpy"
match = '((?!test_).)*\.py'
