name: Mac OS X Full Clean Build with ML
env:
  OPENBB_ENABLE_QUICK_EXIT: true
  OPENBB_LOG_COLLECT: false
  OPENBB_USE_ION: false
  OPENBB_USE_PROMPT_TOOLKIT: false
  PIP_DEFAULT_TIMEOUT: 100
  PYTHONNOUSERSITE: 1
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      comments:
        required: true
        description: "Test scenario tags"
jobs:
  macos-conda:
    name: MacOS-latest, Conda-latest,  Python 3.9
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Need to fetch more than the last commit so that setuptools-scm can
          # create the correct version string. If the number of commits since
          # the last release is greater than this, the version still be wrong.
          # Increase if necessary.
          fetch-depth: 100
          # The GitHub token is preserved by default but this job doesn't need
          # to be able to push to GitHub.
          persist-credentials: false

      - name: Setup caching for conda packages
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-macos-3-9-${{ hashFiles('build/conda/conda-3-9-env.yaml') }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          channels: conda-forge,defaults
          show-channel-urls: true
          channel-priority: flexible
          environment-file: build/conda/conda-3-9-env.yaml
          activate-environment: testing
          # Needed for caching
          use-only-tar-bz2: true

      - name: Get pip cache dir
        shell: bash -l {0}
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: macos-3-9-pip-${{ hashFiles('**/requirements-full.txt') }}
          restore-keys: |
            macos-pip-

      - name: Uninstall Brotlipy
        shell: bash -l {0}
        run: |
          conda remove brotlipy -y

      - name: Install dependencies (Bash)
        shell: bash -l {0}
        run: |
          conda info
          pip install --requirement requirements-full.txt

      - name: List installed packages (Bash)
        shell: bash -l {0}
        run: |
          conda list
          pip list

      - name: Run tests (Bash)
        shell: bash -l {0}
        run: pytest tests/

      - name: Start Terminal and exit
        shell: bash -l {0}
        run: python terminal.py
